## Oh-My-ZSH config
export ZSH=$HOME/.oh-my-zsh

plugins=(jsontools timer python pylint docker direnv command-not-found)
DISABLE_AUTO_UPDATE=true
DISABLE_UPDATE_PROMPT=true

ZSH_THEME="robbyrussell"
HYPHEN_INSENSITIVE="true"

zstyle ':omz:update' mode disabled  # disable automatic updates

plugins+=(git)
DISABLE_UNTRACKED_FILES_DIRTY="true" 

plugins+=(nvm)
NVM_AUTOLOAD=1
NVM_LAZY=1

export EDITOR="code --reuse-window --wait"

if [ -e $WORKSPACE/.zshrc ]; then source $WORKSPACE/.zshrc; fi
source $ZSH/oh-my-zsh.sh